# Generated by Django 5.2.8 on 2025-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("baseQty", models.IntegerField()),
                ("baseVal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("curQty", models.IntegerField()),
                ("curVal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("corpus", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "portfolio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "companies",
                    models.ManyToManyField(
                        blank=True, related_name="teams", to="Stock.company"
                    ),
                ),
            ],
        ),
    ]
