# Generated by Django 5.2.8 on 2025-11-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Stock.company"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Stock.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "company")},
            },
        ),
    ]
