# Generated by Django 5.2.8 on 2025-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stock", "0002_shareallocation_alter_team_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="companies",
            field=models.ManyToManyField(
                related_name="teams",
                through="Stock.ShareAllocation",
                to="Stock.company",
            ),
        ),
    ]
